update webApp files
francisjodi/portfolio pull request #2
Opened 2021-06-06 04:30 UTC by francisjodi

2021-06-08 15:24 UTC, sammcd requested changes
Looks good. My only request is that does the coding nepal code used require any attribution or have any limitations on their license?

2021-06-08 15:24 UTC, sammcd commented on portfolio/src/main/webapp/index.html
> +    <!-- teams section start
May want to consider deleting the commented out code if it is no longer useful.

2021-06-08 15:24 UTC, sammcd commented on portfolio/src/main/webapp/index.html
> +        <!-- <span>Created By <a href="https://www.codingnepalweb.com">CodingNepal</a> | <span class="far fa-copyright"></span> 2020 All rights reserved.</span> -->
Re-using code is great, but is there a license for the code you could link to? Does this require any attribution requirements where they ask to leave this sort of comment?

2021-06-08 15:24 UTC, sammcd commented on portfolio/src/main/webapp/index.html
> +                <!-- <div class="card">
Can possibly delete the commented out code.

2021-06-10 20:04 UTC, mikeshen reviewed
Hey Jodi, I saw you added your week 2 changes! Thanks very much. However, can we actually do these changes as a separate pull request? Let's get this PR into a state with just the week 1 changes, and then I can approve.

2021-06-10 20:07 UTC, mikeshen commented
[Github - About pull requests](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) has a lot of good info on the basic workflow of a Pull Request. Do message me if you can't figure out how to take off commits from a PR. I an walk you through the process.

2021-06-10 22:40 UTC, mikeshen commented
Approved, week 1 changes look great!

2021-06-10 22:41 UTC, mikeshen approved these changes
Approved

2021-06-10 22:42 UTC, merged